name: AR Building v2
version: "1.1.0"
slug: ar_building_v3
description: AR-Guided Tour PWA für historische Konzerthäuser
arch:
  - amd64
  - aarch64
startup: application
boot: auto
host_network: true
init: false
ingress: true
ingress_port: 8099
panel_icon: mdi:cog-outline
panel_title: AR Building Admin
options:
  https_port: 8444
  reset_admin: false
schema:
  https_port: port
  reset_admin: bool
dns:
  - 8.8.8.8
  - 1.1.1.1
